name: build-deploy-runner
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.17.0
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: git config user.email "gf95@divcodes.com"
      - run: git config user.name "tiger99"
      - run: git remote add origin "https://github.com/Gibran-Fahed/Gibran-Fahed.github.io.git"
      - run: npm run deploy
